name: utili
version: '3.3'

services:

    postgres:
        container_name: utili-postgres
        image: postgres
        volumes:
            - './postgresql-data:/var/lib/postgresql/data'
        restart: unless-stopped
        environment:
            POSTGRES_USER: utili
            POSTGRES_PASSWORD: password
            POSTGRES_DB: utili

    bot:
        container_name: utili-bot
        build:
            context: './src'
            dockerfile: './Utili.Bot/Dockerfile'
        depends_on:
            - 'postgres'
        volumes:
            - './config/bot.json:/app/appsettings.json:ro'
            - './bot-logs:/app/logs'
        restart: unless-stopped
        logging:
            driver: "local"
            options:
                max-size: 50M

    backend:
        container_name: utili-backend
        build:
            context: './src'
            dockerfile: './Utili.Backend/Dockerfile'
        depends_on:
            - 'bot'
        volumes:
            - './config/backend.json:/app/appsettings.json:ro'
            - './aspnet-data:/root/.aspnet'
            - './backend-logs:/app/logs'
        restart: unless-stopped
        logging:
            driver: "local"
            options:
                max-size: 50M

    frontend:
        container_name: utili-frontend
        build:
            context: './src/Frontend/'
            dockerfile: 'Dockerfile'
        volumes:
            - './config/frontend.js:/build/config.js:ro'
            - './config/nginx.conf:/etc/nginx/nginx.conf:ro'
            - '/etc/letsencrypt:/etc/letsencrypt:ro'
        ports:
            - '443:443'
            - '80:80'
        restart: unless-stopped
