name: Utili
version: '3.3'

services:

    postgres:
        container_name: utili-postgres
        image: postgres
        volumes:
            - './postgresql-data:/var/lib/postgresql/data'
        restart: always
        environment:
            POSTGRES_USER: utili
            POSTGRES_PASSWORD: password
            POSTGRES_DB: utili

    bot:
        container_name: utili-bot
        build:
            context: './src'
            dockerfile: './Utili.Bot/Dockerfile'
        depends_on:
            - 'postgres'
        volumes:
            - './config/bot.json:/app/appsettings.json:ro'
            - './bot-logs:/app/logs'
        restart: always
        logging:
            driver: "local"
            options:
                max-size: 50M

    backend:
        container_name: utili-backend
        build:
            context: './src'
            dockerfile: './Utili.Backend/Dockerfile'
        depends_on:
            - 'bot'
        volumes:
            - './config/backend.json:/app/appsettings.json:ro'
            - './aspnet-data:/root/.aspnet'
            - './backend-logs:/app/logs'
        restart: always
        logging:
            driver: "local"
            options:
                max-size: 50M

    frontend:
        container_name: utili-frontend
        build:
            context: './src/Frontend/'
            dockerfile: 'Dockerfile'
        volumes:
            - './config/frontend.js:/build/config.js:ro'
            - './config/nginx.conf:/etc/nginx/nginx.conf:ro'
            - '/etc/letsencrypt:/etc/letsencrypt:ro'
        ports:
            - '443:443'
            - '80:80'
        restart: always

    hastebin_postgres:
        container_name: utili-hastebin-postgres
        image: postgres
        volumes:
            - './hastebin-postgresql-data:/var/lib/postgresql/data'
        restart: always
        environment:
            POSTGRES_USER: hastebin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: hastebin

    hastebin:
        container_name: utili-hastebin
        build:
            context: './src/Hastebin/'
            dockerfile: 'Dockerfile'
        depends_on:
            - 'hastebin_postgres'
        volumes:
            - './hastebin-data:/usr/src/app/data'
        environment:
            STORAGE_TYPE: 'postgres'
            DATABASE_URL: 'postgres://hastebin:password@hastebin_postgres:5432/hastebin'
            KEY_LENGTH: 32
            KEYGENERATOR_TYPE: 'random'
            KEYGENERATOR_KEYSPACE: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
            STORAGE_EXPIRE_SECONDS: 2592000
