name: Utili
version: '3.3'
services:
    backend:
        build:
            context: '.'
            dockerfile: 'Utili.Backend/Dockerfile'
        depends_on:
            - 'postgres'
        volumes:
            - './backend.json:/app/appsettings.json:ro'
        ports:
            - '443:443'
            - '80:5000'
            - '5000:5000'
    bot:
        build:
            context: '.'
            dockerfile: 'Utili.Bot/Dockerfile'
        depends_on:
            - 'postgres'
            - 'backend'
        volumes:
            - './bot.json:/app/appsettings.json:ro'
    postgres:
        image: postgres
        restart: always
        volumes:
            - './postgresql-data:/var/lib/postgresql/data'
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: utili
