name: ci

on:
  push:
    branches: [ "main" ]

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    -
      name: Get current date
      id: date
      run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
    -
      name: Debug
      run: echo ${{ steps.date.outputs.date }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: tree
      run: ls -la
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/Frontend/Dockerfile
        tags: 230daniel/utili-frontend:${{ steps.date.outputs.date }}
