name: ci

on:
  push:
    branches: [ "main" ]

jobs:

  build-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./src
        file: ./src/Utili.Bot/Dockerfile
        push: true
        tags: 230daniel/utili-bot:{{ steps.date.outputs.date }}
