name: ci

on:
  push:
    branches: [ "main" ]

jobs:

  build-bot:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get current date
      id: date
      run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./src
        file: ./src/Utili.Bot/Dockerfile
        tags: 230daniel/utili-bot:${{ steps.date.outputs.date }}
        push: true

  build-backend:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get current date
      id: date
      run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./src
        file: ./src/Utili.Backend/Dockerfile
        tags: 230daniel/utili-backend:${{ steps.date.outputs.date }}
        push: true

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get current date
      id: date
      run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./src/Frontend
        file: ./src/Frontend/Dockerfile
        tags: 230daniel/utili-frontend:${{ steps.date.outputs.date }}
        push: true
